#!/bin/sh

. /etc/rc.subr

name="mastodon-node"
rcvar=mastodon_node_enable

load_rc_config ${name}

start_cmd="${name}_start"
stop_cmd="${name}_stop"
pidfile="/var/run/${name}.pid"
PATH=${PATH}":/usr/local/bin"
logfile="/var/log/${name}.log"

: ${mastodon_node_user="mastodon"}
: ${mastodon_node_home="/home/mastodon/live"}


mastodon-node_start()
{
	touch ${pidfile} && chmod ag+wr ${pidfile}
	touch ${logfile} && chmod ag+wr ${logfile}
	su - ${mastodon_node_user} -c "cd ${mastodon_node_home} && env NODE_ENV=production npm run start > ${logfile} 2>&1  &"
	sleep 5
	echo "slept"
	ps ax -U ${mastodon_node_user} | grep "_babel_node " | head -n 1 | awk '{print $1;}' | tee ${pidfile}
	echo "${name} start."
}

mastodon-node_stop()
{
	cd ${MASTODON_HOME}
	kill `cat ${pidfile}`
	echo "${name} stop."
}

run_rc_command $1
